__END__

=head1 NAME

=over 2

B<zfsbootmenu> - System integrations 

=back

=head1 SYNOPSIS

=over 2

ZFSBootMenu behavior is controlled through kernel command line options and ZFS filesystem properties.

=back

=head1 CLI Parameters 

=over 4 

These options are set on the kernel command line when booting the initramfs or UEFI bundle. Default options were carefully chosen so that a system can be booted without setting any values.

=back

=over 4

=item B<spl_hostid=>

When creating an initramfs or UEFI bundle, the I<hostid> from the system is copied into the target. If this image will be used on another system with a different I<hostid>, it can be overridden with this option. 

=item B<force_import=0|1>

Set this option to I<1> to attempt to force a pool import on the system. This enables I<-f> on the I<zpool import> command, which will attempt to import a pool that's potentially in use on another system. Use this option with caution!

=item B<timeout=>

This option controls if the boot environment menu should be displayed.

=over 2

=item B<0> 

Set this to bypass the menu and immediately boot the configured I<bootfs> pool property.

=item B<-1>

Set this to always display the boot environment menu.

=item B<Positive integer>

Set any positive integer to display a countdown timer before booting the configured I<bootfs> boot environment.

=back

=item B<zfsbootmenu:POOL=>

The boot menu module will automatically start if it's included in an initramfs. However, if your system has multiple ZFS pools, you can set one as a primary pool. This is set via I<zfsbootmenu:POOL=>B<pool>

=back

=head1 ZFS Properties 

=over 4

The following properties can be set at any level of the pool to control boot behavior.

=back

=over 4

=item B<org.zfsbootmenu:kernel>

This can be a partial kernel name (I<5.4>) or a full filename (I<vmlinuz-5.7.11_1>).

=item B<org.zfsbootmenu.commandline>

Set the list of kernel commandline options to be passed to the final OS. Do not set I<root=>, this is set for you.

=item B<org.zfsbootmenu:active>

This controls whether boot environments appear in or are hidden from ZFSBootMenu.

=over 2

=item B<off>

Set to B<off> on a boot environment with I<mountpoint=/> to B<HIDE> the environment.

=item B<on>

Set to B<on> for a boot environment with I<mountpoint=legacy> to B<SHOW> the environment. By default ZFSBootMenu only presents boot environments that have I<mountpoint=/> set. Note that not all Linux distributions support booting from filesystems with I<mountpoint=legacy>.

=back

=item B<org.zfsbootmenu:rootprefix>

This controls the prefix added to the ZFS filesystem provided as the root to the kernel booted by ZFSBootMenu. For example, the command-line argument I<root=zfs:zroot/ROOT/void> has the root prefix I<root=zfs:>, which is the default value unless the boot environment appears to be I<Arch Linux>; for arch, the default root prefix is I<zfs=>. Set this property to override the value determined from inspecting the boot environment.

=back

=head1 AUTHOR

ZFSBootMenu Team

=cut
