=head1 NAME

B<zfsbootmenu> - System integration

=head1 SYNOPSIS

ZFSBootMenu behavior is controlled through ZFS filesystem properties and command-line options provided to the ZFSBootMenu kernel.

=head1 Command-Line Parameters

These options are set on the kernel command line when booting the initramfs or UEFI bundle. Default options were chosen to allow general systems to boot without setting any values.

=over 4

=item B<spl_hostid=E<lt>hostidE<gt>>

When creating an initramfs or UEFI bundle, the I<hostid> from the system is copied into the target. If this image will be used on another system with a different I<hostid>, it can be overridden with this option.

Replace B<E<lt>hostidE<gt>> with an eight-digit hexadecimal number.

=item B<force_import=1>

Set this option to attempt to force pool imports. When set, this invokes I<zpool import -f> in place of the regular I<zpool import> command, which will attempt to import a pool that's potentially in use on another system. Use this option with caution!

Omit this option or explicitly specify B<force_import=0> to disable forced imports.

=item B<timeout>

This option accepts numeric values that control whether and when the
boot-environment menu should be displayed.

=over 2

=item B<timeout=0>

When possible, bypass the menu and immediately boot a configured I<bootfs> pool property.

=item B<timeout=-1>

Rather than present a countdown timer for automatic selection, immediately display the boot-environment menu.

=item B<timeout=E<lt>positive integerE<gt>>

Display a countdown timer for the specified number of seconds before booting the configured I<bootfs> boot environment.

=back

=item B<root=zfsbootmenu:POOL=E<lt>poolE<gt>>

By default, ZFSBootMenu will look for the I<bootfs> property on the first pool it imports to select the default boot environment. If you have multiple pools, substitute the name of your preferred pool for B<E<lt>poolE<gt>> in the argument B<root=zfsbootmenu:POOL=E<lt>poolE<gt>>.

=item B<zbm.tmux>

Indicate that ZFSBootMenu should be run under B<tmux> in the initramfs. With this enabled, debug-level logging for the ZFSBootMenu scripts can be easily viewed. The tooling must also be installed with an additional dracut configuration option listed below.

=back

=head1 ZFS Properties

The following properties can be set at any level of the boot-environment hierarchy to control boot behavior.

=over 4

=item B<org.zfsbootmenu:kernel>

An identifier used to select which kernel to boot among all kernels found in the I</boot> directory of the selected boot environment. This can be a partial kernel name (e.g., I<5.4>) or a full filename (e.g., I<vmlinuz-5.7.11_1>).

If the identifier does not match any kernels, the latest kernel will be chosen as a fallback.

=item B<org.zfsbootmenu:commandline>

A list of command-line arguments passed to the kernel selected by ZFSBootMenu for final boot.

Do not set I<root=>; ZFSBootMenu will set this option for for you.

=item B<org.zfsbootmenu:active>

This controls whether boot environments appear in or are hidden from ZFSBootMenu.

=over 2

=item B<off>

For boot environments with I<mountpoint=/>, set B<org.zfsbootmenu:active=off> to B<HIDE> the environment.

=item B<on>

For boot environments with I<mountpoint=legacy>, set B<org.zfsbootmenu:active=on> to B<SHOW> the environment.

=back

By default, ZFSBootMenu only shows boot environments with the property I<mountpoint=/>.

=item B<org.zfsbootmenu:rootprefix>

This specifies the prefix added to the ZFS filesystem provided as the root filesystem on the kernel command line. For example, the command-line argument I<root=zfs:zroot/ROOT/void> has root prefix I<root=zfs:>.

The default prefix is I<root=zfs:> on all systems except those that appear to be Arch Linux. For Arch, the default root prefix is I<zfs=>.

Set this property to override the value determined from inspecting the boot environment.

=back

=head1 Dracut Options

In addition to standard dracut configuration options, the ZFSBootMenu dracut module supports addtional options to customize boot behavior.

=over 4

=item B<zfsbootmenu_setup=E<lt>executable-listE<gt>>

An optional variable specifying a space-separated list of paths to setup hooks that will be installed in the ZFSBootMenu initramfs. Any path in the list B<E<lt>executable-listE<gt>> that exists and is executable will be installed.

Any installed hooks are run right before the ZFSBootMenu menu will be presented; ZFS pools will generally have been imported and the default boot environment will be available in the I<BOOTFS> environment variable. Hooks will not be run if the countdown timer expires (or was set to zero) and the default boot environment is automatically selected. B<Note:> The hooks may be run multiple times if the menu is invoked multiple times, e.g., by dropping to an emergency shell and then returning to the menu. If a script should only run once, the script is responsible for keeping track of this.

=item B<zfsbootmenu_teardown=E<lt>executable-listE<gt>>

An optional variable specifying a space-separated list of paths to teardown hooks that will be installed in the ZFSBootMenu initramfs. Any path in the list B<E<lt>executable-listE<gt>> that exists and is executable will be installed.

Some hardware initialized by the kernel used to boot ZFSBootMenu may not be properly reinitialized when a boot environment is launched. Any teardown hooks installed into the ZFSBootMenu initramfs, will be run immediately before B<kexec> is invoked to jump into the selected kernel. This script can be used, for example, to unbind drivers from hardware or remove kernel modules.

=item B<zfsbootmenu_tmux=true>

An optional variable enabling the installation of B<tmux> and a minimal B<tmux.conf> in the initramfs.

=item B<zfsbootmenu_tmux_conf=E<lt>tmux.confE<gt>>

An optional variable specifying the path to an alternate B<tmux> configuration file. If this key is set but no file exists at the path B<E<lt>tmux.confE<gt>>, the default configuration file is instead used.

=back

=head1 SEE ALSO

B<generate-zbm>(5) B<generate-zbm>(8) B<dracut.conf>(5)

=head1 AUTHOR

ZFSBootMenu Team L<https://github.com/zbm-dev/zfsbootmenu>

=cut
