#!/bin/bash
BASE="$( mktemp -d /tmp/zfs.XXXX )"
fs="$( zfs list -H -o name ${1} )"

if [ "$fs" != "${1}" ]; then
  echo "Filesystem $1 doesn't exist"
  exit
fi

mount -o zfsutil -t zfs "${1}" "${BASE}"
mount -t proc proc "${BASE}/proc"
mount -t sysfs sys "${BASE}/sys"
mount -B /dev "${BASE}/dev"
mount -B /tmp "${BASE}/var/tmp"
mount -t devpts pts "${BASE}/dev/pts"

chroot "${BASE}" /bin/bash

umount "${1}"
