=pod

=head1 NAME

B<zfsbootmenu> - Recovery Shell

=head1 Common Commands

=over 2

=item I<zfsbootmenu>

Launch the interactive boot environment menu.

=item I<zfs-chroot> B<zfs filesystem>

Enter a chroot of the specified boot environment. The boot environment is mounted I<read/write> if the zpool is imported I<read/write>.

=item I<set_rw_pool> B<pool>

Export, then re-import the pool I<read/write>.

=item I<set_ro_pool> B<pool>

Export, then re-import the pool I<read-only>.

=item I<mount_zfs> B<zfs filesystem>

Mount the filesystem at a unique location and print the mount point.

=item I<help>

View the online help system.

=item I<logs>

View warning/error/debug logs.

=back

=head2 AUTHOR

ZFSBootMenu Team L<https://github.com/zbm-dev/zfsbootmenu>

=cut
