=pod

=head1 ZPOOL Health

=over 2

=item I<[MOD+R]> B<rewind checkpoint>

If a pool checkpoint is available, the selected pool is exported and then imported with the I<--rewind-to-checkpoint> flag set.

The operation will fail gracefully if the pool can not be set I<read/write>.

=item I<[MOD+L]> B<view logs>

View logs, as indicated by I<[!]>. The indicator will be yellow for warning conditions and red for errors.

=back

=head2 AUTHOR

ZFSBootMenu Team L<https://github.com/zbm-dev/zfsbootmenu>

=cut
