#!/bin/bash
# vim: softtabstop=2 shiftwidth=2 expandtab

# shellcheck disable=SC1091
source /lib/profiling-lib.sh >/dev/null 2>&1 || true
source /etc/zfsbootmenu.conf >/dev/null 2>&1 || exit 1
source /lib/kmsg-log-lib.sh >/dev/null 2>&1 || exit 1
source /lib/zfsbootmenu-core.sh >/dev/null 2>&1 || exit 1

BOOTFS=""
KERNEL=""
CONTEXT=""

while getopts "b:c:k:" opt; do
  case "${opt}" in
    b) BOOTFS="${OPTARG}" ;;
    c) CONTEXT="${OPTARG}" ;;
    k) KERNEL="${OPTARG}" ;;
    *) ;;
  esac
done

shift $((OPTIND - 1))

ENV="${1}"

if [ -z "${KERNEL}" ]; then
  # shellcheck disable=SC2034
  read -r _ KERNEL _ <<< "$( select_kernel "${ENV}" || echo $'-\t-\t-' )"
  [ "${KERNEL}" = "-" ] && KERNEL=""
fi

if [ "${BOOTFS}" = "${ENV}" ]; then
  _EXTRAS+=( "default," )
fi

if be_has_encroot "${ENV}" >/dev/null; then
  _EXTRAS+=( "encrypted," )
fi

pool="${ENV%%/*}"
if is_writable "${pool}" ; then
  _EXTRAS+=( "r/w" )
  _COLOR="red"
else
  _EXTRAS+=( "r/o" )
  _COLOR="green"
fi

selected_arguments="$( center_string "$( load_be_cmdline "${ENV}" "${KERNEL}" )" )"

KERNEL="${KERNEL##*/}"
selected_env_str="$( center_string "${ENV} (${_EXTRAS[*]}) - ${KERNEL:-missing}" )"

# colorize doesn't automatically add a newline
if [ -f "${BASE}/have_errors" ]; then
  selected_env_str="${selected_env_str:3}"
  colorize "red" "[!]"
elif [ -f "${BASE}/have_warnings" ]; then
  selected_env_str="${selected_env_str:3}"
  colorize "yellow" "[!]"
fi

colorize "${_COLOR}" "${selected_env_str}\n"
echo "${selected_arguments}"

if [ -n "${CONTEXT}" ]; then
  colorize "orange" "$( center_string "${CONTEXT}" )"
fi
