#!/bin/bash
# vim: softtabstop=2 shiftwidth=2 expandtab

# shellcheck disable=SC1091

sources=(
  /lib/profiling-lib.sh
  /etc/zfsbootmenu.conf
  /lib/kmsg-log-lib.sh
)

for src in "${sources[@]}"; do
  # shellcheck disable=SC1090
  source "${src}" >/dev/null 2>&1 || exit 1
done

hook_stage="${1}"

if [ -z "${hook_stage}" ]; then
  zerror "required hook stage undefined"
  exit 1
fi

if [ -d "/libexec/${hook_stage}" ]; then
  for _hook in /libexec/"${hook_stage}"/*; do
    if [ -x "${_hook}" ]; then
      zinfo "processing ${_hook}"
      "${_hook}"
    fi
  done
fi
