name: Docs check
on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: Check Docs
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-linux:latest-full-x86_64
    steps:
      - name: Prepare container
        run: |
          xbps-install -Syu || xbps-install -y xbps
          xbps-install -yu
          xbps-install -y chroot-git make
      - uses: actions/checkout@master
      - name: Prepare environment
        run: cd docs && make SUDO= INSTALLOPTS=-yu setup-void
      - name: Linkcheck
        run: cd docs && make SPHINXOPTS=--color linkcheck
