name: Lint documentation
on: [ push ] 

jobs:
  documentation:
    name: Lint documentation 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run pod2man 
      run: releng/pod2man.sh "${GITHUB_SHA}"

    - name: Run pod2help
      run: releng/pod2help.sh

